python/Django/Day_15/boards/urls.py
from django.urls import path
from . import views

app_name='boards'

urlpatterns = [
    path('',views.index,name='index'),
    path('/new/',views.new,name='new'),
    path('<int:b_id>/',views.detail,name="detail"),
    path('edit/<int:b_id>/',views.edit, name='edit'),
    path('delete/<int:b_id>/',views.delete, name='delete')

]

python/Django/Day_15/boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
    title=models.CharField(max_length=30)
    content=models.CharField(max_length=200)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    

python/Django/Day_15/boards/forms.py
from django import forms
from .models import Board

class BoardForm(forms.ModelForm):
    class Meta:
        #meta는 
        model = Board
        fields = ['title','content']

python/Django/Day_15/boards/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import BoardForm
from .models import Board
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):

    boards = Board.objects.all()

    context = {
        'boards':boards
    }
    return render(request,'boards/index.html',context)

@login_required
def new(request):
    # if request.user.is_authenticated:
    #     return redirect('boards:index')
        #로그인 상태에서 새로운 회원가입이나 로그인이 안되게 막는 코드
        
    if request.method == "POST":
        form = BoardForm(request.POST)

        if form.is_valid():
            board = form.save(commit=False)
            return redirect('boards:index')


    else:
        form = BoardForm()

    context={
        'form':form
    }
    return render(request,'boards/new.html',context)

def detail(request, b_id):
    board = get_object_or_404(Board,id=b_id)

    context={
        'board':board
    }
    return render(request,'boards/detail.html',context)

def edit(request, b_id):
    board = get_object_or_404(Board,id=b_id)

    if request.user != board.user:
        return redirect('boards:index')

    if request.method =="POST":
        form=BoardForm(request.POST, instance=board)
        if form.is_valid():
            board=form.save()
            return redirect("boards:detail",board.id)
    else:
        form = BoardForm(instance=board)\
       


    context={
        'form':form
    }

    return render(request,'boards/edit.html',context)

def delete(request, b_id):
    board = get_object_or_404(Board,id=b_id)

    if request.user != boards.user:
        return redirect('boards:index')

    if request.method =="POST":
        board.delete()
        return redirect('boards:indext')
    
    return redirect('boards:detail',board.id)

python/Django/Day_15/boards/templates/boards/detail.html
{% extends 'base.html' %}
{% block body %}
<table>
    <tr>
        <td>title</td>
        <td>{{ board.title }}</td>
    </tr>
    <tr>
        <td>content</td>
        <td>{{ board.content }}</td>
    </tr>
</table>
{% if user == board.user %}
<a href="{% url 'boards:edit' board.id %}">수정하기</a>
<form action="{url 'boards:delete' board.id}" method="post">
    {% csrf_token %}
    <a href="#" onclik="this.parentsNode.submit()">삭제하기</a>
</form>
{% endif %} 
{% endblock %}

python/Django/Day_15/boards/templates/boards/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="수정하기">
</form>
{% endblock %}

python/Django/Day_15/boards/templates/boards/index.html
{% extends 'base.html' %}
{% block body %}
<h1>index page</h1>
<ul>
    {% for board in boards %}
        <li>  <a href="{% url 'boards:detail' board.id %}">{{ board.title }} - </a {{ user }}></li>
    {% endfor %}
</ul>
<a href="{% url 'boards:new' %}">새글쓰기</a>
{% if user.is_authenticated %}
<form action='{% url "accounts:logout" %}' method='POST' >
    {% csrf_token %}
    <a href="#" onclick="this.parentNode.submit()">로그아웃</a>
    <input type = 'submit'>
</form>
{% else %}
<a href="{% url 'accounts:signup' %}">회원가입</a>
<a href="{% url 'accounts:login' %}">로그인</a>
{% endif %}
{% endblock %}

python/Django/Day_15/boards/templates/boards/new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="새글 쓰기">
</form>
{% endblock %}