python/Django/Day_14/article/urls.py
from django.urls import path
from . import views

app_name='article'
urlpatterns=[
    path('',views.index,name="index"),
    path('new/', views.new, name ="new"),
    path('<int:a_id>/',views.detail, name="detail"),
    path('<int:a_id>/edit/',views.edit, name="edit"),
    # path('<int:a_id>/delete/',views.delete, name='delete')

]

python/Django/Day_14/article/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=200)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

#     def get_absolute_url(self):
    
#         return reverse('article:detail', args=[self.id])

# class Author(models.Model):
#     name=models.CharField(max_length=20)
#     company=models.CharField(max_length=200)

#     def __str__(self):
#         return self.title

    # def get_absolute_url(self):
    #         return reverse('article:detail', args=[self.id])

python/Django/Day_14/article/forms.py
from django import forms

# check_box = [
#     #(인풋, 아웃풋)
#     ('one',"하나"),
#     ('two',"둘"),
#     ('three',"셋"),
# ]
# MONTH_EN=[]

#     1:('JAN'),2:('FEB'),3:('MAR'),4:('APR'),5:('MAY'),6:('JUN'),7:('JUL'),8('AGU')
    
#     ]  
class ArticleForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(max_length=5,help_text="5자리만 입력하세요.")
    
    # #체크박스
    # content = forms.MultipleChoiceField(
    #     widget=forms.CheckboxSelectMultiple,
    # )
    # #라디오박스
    # content=forms.ChoiceField(
    #     widget=forms.RadioSelect,
    #     choices=check_box
    # )
    # #드랍다운
    # content = forms.ChoiceField(
    #     widget=forms.Select,
    #     choices=check_box
    # )

    #날짜
    # content =forms.DateField(
    #     widget=forms=SelectDateWidget(
    #         years=range(1990,2020),
    #         MONTH_EN
    #     )      
#     # )
        
# class Authorform(forms.ModelForm):
#     class Meta: 
#         model =Author
#         field=['name','company']

python/Django/Day_14/article/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm
from IPython import embed
from django.urls import reverse

# Create your views here.
def index(request):
    #embed()
    aritlces = Article.objects.all()
    context={
        "articles = articles"
    }
    return render(request, 'article/index.html')

def new(request):
    if request.method=="POST":
        # title=request.POST.get('title')
        # content=request.POST.get('content')
        # article=Article()
        # article.title=title
        # article.content=conetent
        # article.save()
        form = ArticleForm(request.POST)
        #embed()
        if form.is_valid(): #유효성검사 이상없으면True 출력
            author=form.save()
            # title = form.cleaned_data.get('title')
            # content = form.cleaned_data.get('content')
            # article = Article.objects.create(title=title,content=content)

            return redirect('article:index')

        #return redirect('article:index')
    else:
        form = ArticleForm()

    context ={
        "form" : form
        }

    return render(request,'article/new.html',context)

def detail(request, a_id):
    article =Article.objects.get(id=a_id)
    context={
        "article":article
    }
    
    return render(request,'article/detail.html', context)

def edit(request,a_id):
    #article = Article.objects.get(id=a_id)
    article = get_object_or_404(Article,id=a_id)

    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article.title = form.cleaned_data.get('title')
            article.content=form.cleaned_data.get('content')
            article.save()
            return redirect(article)
            #return redirect('article:detail',article.id)
    else:
        
        form = ArticleForm(initial=article.__dict__)
        #embed()
    context = {
        'form':form
    }
    return render(request,'article/new.html',context)
    
# def delete(request, a_id):
#     aritcle = Article.objects.get(id=a_id)
#     if request.method == "POST":
#        article.delete()

#         return redirect("aritcle/detail")
#     else:
#         return 

def get_absolute_url(self):
    return reverse('article:detail',args=[self.id])

python/Django/Day_14/article/templates/article/detail.html
{% extends 'base.html' %}
{% block body %}
    <p>Tile : {{ article.title }}</p>
    <p>CONTENT : {{ article.content }}</p>
    <a href="{% url 'article:edit' article.id %}">수정하기</a>
    <form action="{% url 'article:delete' %}" method = "POST">
        
            {% csrf_token %}
            <a href="#" onclick="this.parentNode.submit()"></a>
    </form>
{% endblock %}

python/Django/Day_14/article/templates/article/index.html
{% extends 'base.html' %}
{% block body %}
    <h1>Index page</h1>
    <ul>
        {% for aritlce in articles %}
        <li><a href="{% url 'article:detaial' aritcle.id %}>"></a> {{aritcle.tile}} </li>
        {% endfor %}
    </ul>
    <a href="{% url 'article:new' %}">새로만들기</a>
{% endblock %}

python/Django/Day_14/article/templates/article/new.html
{% extends 'base.html' %}
{% block body %}
<!-- new -->
<form action='' method='POST' >
        {% csrf_token %}
        <!-- TITILE : <input type="text" name="tiel"><br>
        CONTENT:<br>
        <textarea name="content" id="" cols="30" rows="10"></textarea> -->
        <table>
            {{ form.as_table }}
        </table>
        <p>
            <input type = 'submit'>
        </p>    
{% endblock %}